var users = {
	"id": 20,
	"groupName": "Editor-TestAccounts",
	"list": [{
		"id": 8,
		"name": "Robin",
		"admin": true
	}, {
		"id": 12,
		"name": "Daniel",
		"admin": true
	}, {
		"id": 41,
		"name": "Christian Henzler",
		"admin": false
	}, {
		"id": 12559,
		"name": "schickore",
		"admin": false
	}, {
		"id": 12596,
		"name": "Diego Jannuzzo",
		"admin": false
	}, {
		"id": 13191,
		"name": "geogebra",
		"admin": false
	}, {
		"id": 17655,
		"name": "cb4d3r",
		"admin": false
	}, {
		"id": 17886,
		"name": "mmenke",
		"admin": false
	}, {
		"id": 8798,
		"name": "lionsports",
		"admin": false
	}]
}

var users_others = {
	list: [{
		"id": 18656,
		"name": "bfgs",
		"admin": false
	}, {
		"id": 22242,
		"name": "haraldfuchs",
		"admin": false
	}, {
		"id": 24084,
		"name": "chschett",
		"admin": false
	}, {
		"id": 24939,
		"name": "berhausen",
		"admin": false
	}, {
		"id": 26538,
		"name": "muschtho",
		"admin": false
	}, {
		"id": 27708,
		"name": "Fujikatoma",
		"admin": false
	}, {
		"id": 30084,
		"name": "Nuki",
		"admin": false
	}, {
		"id": 57525,
		"name": "cschlegel",
		"admin": false
	}, {
		"id": 57573,
		"name": "wilkensa",
		"admin": false
	}, {
		"id": 57663,
		"name": "hpatz",
		"admin": false
	}, {
		"id": 58048,
		"name": "hkarrasch",
		"admin": false
	}, {
		"id": 58107,
		"name": "onlinemekteb",
		"admin": false
	}, {
		"id": 59329,
		"name": "kraeml2",
		"admin": false
	}, {
		"id": 59828,
		"name": "auhagen",
		"admin": false
	}, {
		"id": 60576,
		"name": "bame",
		"admin": false
	}, {
		"id": 62280,
		"name": "lenehj",
		"admin": false
	}, {
		"id": 64792,
		"name": "kmorisse",
		"admin": false
	}, {
		"id": 64918,
		"name": "tkutzner",
		"admin": false
	}, {
		"id": 66600,
		"name": "ricomeiner",
		"admin": false
	}, {
		"id": 67677,
		"name": "Sicher",
		"admin": false
	}, {
		"id": 68360,
		"name": "UG",
		"admin": false
	}, {
		"id": 68927,
		"name": "FHWS_Kempkes",
		"admin": false
	}, {
		"id": 72037,
		"name": "LuPa",
		"admin": false
	}, {
		"id": 77198,
		"name": "ibussec",
		"admin": false
	}, {
		"id": 78912,
		"name": "potts",
		"admin": false
	}, {
		"id": 86514,
		"name": "Edutainment-Sparkasse",
		"admin": false
	}, {
		"id": 86846,
		"name": "asdasd123",
		"admin": false
	}, {
		"id": 87523,
		"name": "helmut.roderus",
		"admin": false
	}, {
		"id": 88931,
		"name": "KlickItSafeKurs",
		"admin": false
	}, {
		"id": 94481,
		"name": "ute@hlasek.de",
		"admin": false
	}, {
		"id": 94565,
		"name": "beaury",
		"admin": false
	}, {
		"id": 95650,
		"name": "usability",
		"admin": false
	}, {
		"id": 95657,
		"name": "Usertests",
		"admin": false
	}, {
		"id": 99708,
		"name": "mik.gros",
		"admin": false
	}, {
		"id": 100066,
		"name": "umontgomery",
		"admin": false
	}, {
		"id": 101072,
		"name": "e-team",
		"admin": false
	}, {
		"id": 101808,
		"name": "daberstedtkanter",
		"admin": false
	}, {
		"id": 104234,
		"name": "nelkasovic",
		"admin": false
	}, {
		"id": 105261,
		"name": "bankingprof",
		"admin": false
	}, {
		"id": 105393,
		"name": "aklinger",
		"admin": false
	}, {
		"id": 107473,
		"name": "DiSK",
		"admin": false
	}, {
		"id": 108905,
		"name": "f.dippl",
		"admin": false
	}, {
		"id": 114082,
		"name": "iFrameiFrameiFrame",
		"admin": false
	}, {
		"id": 114092,
		"name": "asd asd asd ",
		"admin": false
	}, {
		"id": 114095,
		"name": "1234123",
		"admin": false
	}, {
		"id": 114248,
		"name": "asd asd asd asd asd a",
		"admin": false
	}, {
		"id": 114249,
		"name": "asdkjasldkjasd asd",
		"admin": false
	}, {
		"id": 114250,
		"name": "alksdj alksdja ",
		"admin": false
	}, {
		"id": 114262,
		"name": "stflund",
		"admin": false
	}, {
		"id": 117357,
		"name": "larshamann",
		"admin": false
	}, {
		"id": 118160,
		"name": "gschwed",
		"admin": false
	}, {
		"id": 119277,
		"name": "Philipp",
		"admin": false
	}, {
		"id": 120197,
		"name": "julia.rausenberger",
		"admin": false
	}, {
		"id": 122337,
		"name": "BenjaminZ",
		"admin": false
	}, {
		"id": 124448,
		"name": "sabine",
		"admin": false
	}, {
		"id": 124976,
		"name": "dfleckl",
		"admin": false
	}, {
		"id": 129060,
		"name": "MHiero",
		"admin": false
	}, {
		"id": 129187,
		"name": "DZenker",
		"admin": false
	}, {
		"id": 134835,
		"name": "thomas.klement",
		"admin": false
	}, {
		"id": 137358,
		"name": "jdbeyer",
		"admin": false
	}, {
		"id": 139370,
		"name": "ckbtf84",
		"admin": false
	}, {
		"id": 140547,
		"name": "burkleh",
		"admin": false
	}, {
		"id": 142270,
		"name": "sroever",
		"admin": false
	}, {
		"id": 142440,
		"name": "Leuchte",
		"admin": false
	}, {
		"id": 143978,
		"name": "wangler",
		"admin": false
	}, {
		"id": 144937,
		"name": "fvd",
		"admin": false
	}, {
		"id": 145279,
		"name": "test_capira_safasdfsadfasdfas",
		"admin": false
	}, {
		"id": 145296,
		"name": "unrecognized",
		"admin": false
	}, {
		"id": 146760,
		"name": "bsiegel",
		"admin": false
	}, {
		"id": 147365,
		"name": "cgi1159",
		"admin": false
	}, {
		"id": 149312,
		"name": "phst2010@gmail.com",
		"admin": false
	}, {
		"id": 155341,
		"name": "herb37",
		"admin": false
	}, {
		"id": 166482,
		"name": "actxc",
		"admin": false
	}, {
		"id": 171494,
		"name": "frankrumpel",
		"admin": false
	}, {
		"id": 179462,
		"name": "cgertler",
		"admin": false
	}, {
		"id": 180539,
		"name": "anja.nuss",
		"admin": false
	}, {
		"id": 193180,
		"name": "kosswa",
		"admin": false
	}, {
		"id": 195060,
		"name": "the_librarian",
		"admin": false
	}, {
		"id": 196831,
		"name": "econn",
		"admin": false
	}, {
		"id": 207373,
		"name": "werner",
		"admin": false
	}, {
		"id": 208536,
		"name": "E-Learning@UniWuppertal",
		"admin": false
	}, {
		"id": 215178,
		"name": "elkas",
		"admin": false
	}, {
		"id": 216909,
		"name": "lehrerjoern",
		"admin": false
	}, {
		"id": 217957,
		"name": "ramonfueglister",
		"admin": false
	}, {
		"id": 222403,
		"name": "roland.fuchs@gbssg.ch",
		"admin": false
	}, {
		"id": 222415,
		"name": "rico",
		"admin": false
	}, {
		"id": 222421,
		"name": "Silviorimoli",
		"admin": false
	}, {
		"id": 222455,
		"name": "martinbaenziger",
		"admin": false
	}, {
		"id": 226412,
		"name": "michael54h",
		"admin": false
	}, {
		"id": 228726,
		"name": "PAS_LET",
		"admin": false
	}, {
		"id": 230119,
		"name": "123123123123123123",
		"admin": false
	}, {
		"id": 231632,
		"name": "lernoase",
		"admin": false
	}, {
		"id": 236068,
		"name": "daweb",
		"admin": false
	}, {
		"id": 237026,
		"name": "KevinAtkins",
		"admin": false
	}, {
		"id": 237136,
		"name": "Vorkurs2015",
		"admin": false
	}]
}
